source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-seo-tag", "~> 2.8"

# Required on Ruby 3.4+ where these moved out of stdlib.
gem "csv"
gem "logger"
gem "base64"
